In [1]:
import pandas as pd

dataset=pd.read_csv(r'/Users/pasandevin/My_Files/repo/deep-learning-materials/Day 03- Iris flower and heart risk level prediction models/iris.csv').values
print(dataset,dataset.shape)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [2]:
data=dataset[:,0:4]
target=dataset[:,4]

print(data.shape,target.shape)

(150, 4) (150,)


In [3]:
print(data)
print(target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Categorical Encoding

In [ ]:
from keras.utils import np_utils

new_target=np_utils.to_categorical(target)

print(target[:10])

In [ ]:
print(new_target[:10])

In [ ]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,new_target,test_size=0.1)

In [ ]:
print(train_data,train_data.shape)

In [ ]:
print(test_data,test_data.shape)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()   # empty sequential type neural network

model.add(Dense(64,input_dim=4,activation='relu'))  # 1st Hidden Layer
#model.add(Dense(64,input_shape=(4,),activation='relu'))
model.add(Dense(32,activation='relu')) #2nd Hidden Layer
model.add(Dense(3,activation='softmax')) #output layer

model.compile(loss='categorical_crossentropy',optimizer='adaGrad',metrics=['accuracy'])
model.summary()

In [ ]:
for layer in model.layers:
    
    print('================================',layer.name,'================================')
    
    parameters=layer.get_weights()
    print(parameters)

In [ ]:
# training the model
model.fit(train_data,train_target,epochs=1000,validation_split=0.1,batch_size=1)
#model.fit(train_data,train_target,epochs=1000,validation_data=(test_data,test_target),batch_size=1)

In [ ]:
from matplotlib import pyplot as plt

plt.plot(model.history.history['loss'],label='loss')
plt.plot(model.history.history['val_loss'],label='val loss')
plt.legend()
plt.xlabel('#epoch')
plt.ylabel('loss')
plt.show()

In [ ]:
plt.plot(model.history.history['accuracy'],label='accuracy')
plt.plot(model.history.history['val_accuracy'],label='val accuracy')
plt.legend()
plt.xlabel('#epoch')
plt.xlabel('loss')
plt.show()

In [ ]:
import numpy as np

test_data_1=np.array([5.3,2.3,4.7,2.1]).reshape(1,-1)

predicted_target_1=model.predict(test_data_1)
print(predicted_target_1)

In [ ]:
label=np.argmax(predicted_target_1)
print(label)

In [ ]:
predicted_target=model.predict(test_data)
print(predicted_target)
print(np.argmax(predicted_target,axis=1))

In [ ]:
print(test_target)
print(np.argmax(test_target,axis=1))

In [ ]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(np.argmax(test_target,axis=1),np.argmax(predicted_target,axis=1))
print('accuracy:',acc)

In [ ]:
model.evaluate(test_data,test_target)         #argmax will be automatically added  results= (loss,accuracy)

In [ ]:
model.save_weights('FFNN-iris.h5')

In [ ]:
model.save('FFNN-iris.model')